version: '3.8'

services:
  decimal:
    image: ketan003/decimal-api:v1
    ports:
      - "5100:5100"

  devanagari:
    image: ketan003/devanagari-api:v1
    ports:
      - "5200:5200"

  unified:
    image: ketan003/unified-api:v1
    ports:
      - "5300:5300"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - decimal
      - devanagari
      - unified
